---
- hosts: websever
  tasks:
      
    - name: login to jfrog
      shell: docker login -u mohithdevops9@gmail.com -p Manvith@123 mohitrrr.jfrog.io   
    
    - name: pull an image
      shell: docker pull mohitrrr.jfrog.io/mohith/dharma:v{{BUILD_NUMBER}}

   # - name: remove container
    #  shell: docker rm -f devopsAppDeploy
        
    - name: create a application container
      shell: docker run -id --name devopsAppDeploy -p 8111:8080 mohitrrr.jfrog.io/mohith/dharma:v{{ BUILD_NUMBER }}
 
   
